/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package pe.gob.sucamec.bdintegrado.jsf.util;

/**
*
* @author Renato
*/
public enum EstadoCrud {

BUSCAR, CREAR, EDITAR, VER , BANDEJA, BANDEJAEVA, BANDEJACOO, BANDEJAGER,
CREAREXP, CREARIMP, EDITAREXP, EDITARIMP, VERIMP, VEREXP,
CREARINT, CREARSAL, EDITARINT, EDITARSAL, VERINT, VERSAL,
BANDEJAANULME,CREARANULME, VERANULME,SALDOS, VERSOLREC, VERENTARM, USUAUTORIZADO, USUNOAUTORIZADO,
CREARVERIF, CREARARMA, EDITARVERIF, EDITARARMA, EDITAREMITIDO, VERVERIF, VERARMA, VEREMITIDO,
BUSCAROBS, RECTIFICAR, REPORTE, DECLARAR, BANDEJACESE, BANDEJADEV,
CREAR_TERMINO, EDITAR_TERMINO, VER_TERMINO, PREVIO,
CREAR_ADENDA, EDITAR_ADENDA, VER_ADENDA, DECLARAR_ADENDA,
CONFIRMAR, ACTUALIZAR, RENOVAR, DUPLICAR, CESE,
REDIRECT, IMPRIMIR,
// LIBROS
USO, COMERCIO , FABRICA,
// Solicitudes de Autorización para Prestación de Servicios de Seguridad 
CREARAUTSERVSEG, CREARAUTCAMDOMLEGAL, CREARAUTCAMRPRESLEGAL,
CREARDEP, EDITARDEP, CREARDEV, EDITARDEV, BUSCARGUIA, BUSCARACTA,

// Para Autorizacion de Seguridad
VERSISPE, CREARSISPE, EDITARSISPE, EXISTESISPE,
VERVIGILANCIAPRIVADA, CREARVIGILANCIAPRIVADA, EDITARVIGILANCIAPRIVADA
//para Protección personal
,CREARPROTECCIONPERSONAL, VERPROTECCIONPERSONAL,EDITARPROTECCIONPERSONAL
//para CAMBIO LOCAL
,CREARCAMBIOLOCAL, VERCAMBIOLOCAL,EDITARCAMBIOLOCAL,
//SISPA
VERSISPA, CREARSISPA, EDITARSISPA, EXISTESISPA,
VERSCBC, CREARSCBC, EDITARSCBC,
VERSSE, CREARSSE, EDITARSSE,
VERSTS, CREARSTS, EDITARSTS,
VERSPCP, CREARSPCP, EDITARSPCP,
VERCEFOESP,CREARCEFOESP, EDITARCEFOESP,
VERDEPARTAMENTO,CREARDEPARTAMENTO, EDITARDEPARTAMENTO,
//TRANSPORTE DE DINERO Y VALORES
VERTDV, CREARTDV, EDITARTDV,

//CERTIFICACION DE VEHICULOS BLINDADOS
VERCERTVEHBLIND, CREARCERTVEHBLIND, EDITARCERTVEHBLIND,

//MICROSERVICIOS
CREARTIPOBASE, EDITARTIPOBASE, VERTIPOBASE,
};
